# Generated by Django 4.2.3 on 2024-06-24 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment_app', '0002_alter_user_options_alter_user_managers_user_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('ACCOUNT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('FIRST_NAME', models.CharField(max_length=100)),
                ('LAST_NAME', models.CharField(max_length=100)),
                ('USER_NAME', models.CharField(max_length=100, unique=True)),
                ('BIRTHDATE', models.DateField()),
                ('PHONE_NUMBER', models.CharField(max_length=20)),
                ('EMAIL', models.EmailField(max_length=254, unique=True)),
                ('PASSWORD', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('STREET', models.CharField(max_length=100)),
                ('CITY', models.CharField(max_length=100)),
                ('PROVINCE', models.CharField(max_length=100)),
                ('POSTAL_CODE', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Addresses',
                'unique_together': {('STREET', 'CITY', 'PROVINCE', 'POSTAL_CODE')},
            },
        ),
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('CATEGORY_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CATEGORY_NAME', models.TextField()),
            ],
            options={
                'db_table': 'EquipmentCategory',
            },
        ),
        migrations.CreateModel(
            name='EquipmentDetails',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=100)),
                ('DESCRIPTION', models.TextField()),
                ('IS_ONSITE_ONLY', models.BooleanField()),
                ('WARRANTY_YEARS', models.IntegerField()),
                ('CATEGORY_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_app.equipmentcategory')),
            ],
            options={
                'db_table': 'EquipmentDetails',
            },
        ),
        migrations.CreateModel(
            name='EquipmentReservations',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('BORROW_DATE', models.DateField()),
                ('RETURN_DATE', models.DateField()),
                ('PURPOSE', models.TextField()),
                ('RESERVATION_TYPE', models.CharField(choices=[('onsite', 'Onsite'), ('borrow', 'Borrow')], max_length=10)),
                ('EQUIPMENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_app.equipmentdetails')),
            ],
            options={
                'db_table': 'EquipmentReservations',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_app.inventoryitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_app.order')),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('RESERVATION_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CREATED_DATETIME', models.DateTimeField(auto_now_add=True)),
                ('UPDATED_DATETIME', models.DateTimeField()),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_app.accounts')),
            ],
            options={
                'db_table': 'Reservations',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('ROLE_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ROLE_TYPE', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], max_length=10)),
            ],
            options={
                'db_table': 'Roles',
            },
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.CreateModel(
            name='EquipmentInventory',
            fields=[
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='equipment_app.equipmentdetails')),
                ('LENT', models.IntegerField()),
                ('AVAILABLE', models.IntegerField()),
            ],
            options={
                'db_table': 'EquipmentInventory',
            },
        ),
        migrations.CreateModel(
            name='ReservationStatus',
            fields=[
                ('RESERVATION_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='equipment_app.reservations')),
                ('STATUS', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10)),
            ],
            options={
                'db_table': 'ReservationStatus',
            },
        ),
        migrations.CreateModel(
            name='UserSignupStatus',
            fields=[
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='equipment_app.accounts')),
                ('STATUS', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10)),
            ],
            options={
                'db_table': 'UserSignupStatus',
            },
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='equipment_app.OrderItem', to='equipment_app.inventoryitem'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentreservations',
            name='RESERVATION_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment_app.reservations'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='ADDRESS_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_app.addresses'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='ROLE_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_app.roles'),
        ),
    ]
